[project]
authors = ["Nicholas A. Del Grosso <delgrosso.nick@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "data_extraction"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=25.0.1,<26"

[pypi-dependencies]
numpy = ">=2.2.4, <3"
h5py = ">=3.13.0, <4"
pyyaml = ">=6.0.2, <7"
xmltodict = ">=0.14.2, <0.15"
netcdf4 = ">=1.7.2, <2"
ipykernel = ">=6.29.5, <7"
